<?xml version="1.0" encoding="utf-8"?><Database Name="PDHNLinq" Class="DataUsersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=PDHNLinq;Persist Security Info=True;User ID=sa" SettingsObjectName="Linq.Properties.Settings" SettingsPropertyName="PDHNLinqConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="IdUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Users_Infor" Member="Infor" ThisKey="IdUser" OtherKey="IdUsers" Type="Infor" />
    </Type>
  </Table>
  <Table Name="dbo.Infor" Member="Infor">
    <Type Name="Infor">
      <Column Name="IdInfo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUsers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Users_Infor" Member="Users" ThisKey="IdUsers" OtherKey="IdUser" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
</Database>